import type { Metadata } from "next";
import "../globals.css";
import localFont from 'next/font/local'
import { NextFont } from "next/dist/compiled/@next/font";
import Footer from "@/app/component/Footer/Footer";
import Nav from "../component/Nav/Nav";
import Header from "../component/Header/Header";
import Hero from "../component/Hero/Hero";


const myFont: NextFont = localFont({ src: '../../public/font/Vazirmatn-Regular.woff2' })
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {



    return (
        <html lang="en">
        <body className={[myFont.className, "bg-white"].join(" ")} style={{ direction: "rtl" }}>
        <div className="  mb-[70px] sm:mb-[150px]">
            <Nav />
        </div>
        {children}
        <Footer />
        </body>
        </html>
    );
}
