import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import AdminNavbar from "@/app/admin/Navbar/AdminNavbar";
import Sidebar from "@/app/admin/Sidebar/Sidebar";
import localFont from 'next/font/local'
import {NextFont} from "next/dist/compiled/@next/font";
import {cookies} from "next/headers";
import {me} from "@/app/admin/api/UserApi";


const myFont:NextFont = localFont({ src: '../../public/font/Vazirmatn-Regular.woff2' })
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const token:string|undefined=cookies().get("access-token")?.value;
 let role="";

const Me =await me(token);
role=Me.admin_role;


export default function AdminLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en">
        <body className={myFont.className} style={{direction:"rtl"}}>
        <Sidebar  token={token} role={role}/>
        <div className="relative md:mr-56 bg-blueGray-100">
            <AdminNavbar  token={token}/>
            {children}
        </div>
        </body>
        </html>
    );
}
