import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AdminNavbar from "./admin/Navbar/AdminNavbar";
import Sidebar from "./admin/Sidebar/Sidebar";
import localFont from 'next/font/local'
import {NextFont} from "next/dist/compiled/@next/font";
import Footer from "@/app/component/Footer/Footer";


const myFont:NextFont = localFont({ src: '../public/font/Vazirmatn-Regular.woff2' })
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={myFont.className} style={{direction:"rtl"}}>
         <div className="relative bg-blueGray-100">
             <h1>
                 mehran
             </h1>
             {children}

             <Footer />
        </div>
        </body>
        </html>
    );
}
